//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial_DbSkelaton.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class autogenerateinfo
    {
        public int ID { get; set; }
        public string WebServiceName { get; set; }
        public string TableName { get; set; }
        public string Datacomponentname { get; set; }
        public string BusinessComponentname { get; set; }
        public Nullable<bool> FetchSP { get; set; }
        public Nullable<bool> InsertSP { get; set; }
        public Nullable<bool> UpdateSP { get; set; }
        public Nullable<bool> DeleteSP { get; set; }
        public Nullable<bool> ReturnDataset { get; set; }
        public Nullable<bool> ReturnDataReader { get; set; }
        public Nullable<bool> ReturnDataTable { get; set; }
        public Nullable<bool> SPU_ExecuteNonQuery { get; set; }
        public Nullable<bool> SPU_ExecuteScalar { get; set; }
        public Nullable<bool> ReturnXmlReader { get; set; }
        public Nullable<bool> DeletedFlag { get; set; }
    }
}
