//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial_DbSkelaton.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string DriverNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Town { get; set; }
        public string PostCode { get; set; }
        public string TelNo { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public Nullable<byte> VehicleID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public byte[] UpdatedBy { get; set; }
        public Nullable<bool> DeletedFlag { get; set; }
    }
}
