//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial_DbSkelaton.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsFare
    {
        public int ID { get; set; }
        public decimal BaseRate { get; set; }
        public decimal BaseRatePerDistance { get; set; }
        public string BaseRateDistanceType { get; set; }
        public Nullable<decimal> StartMeterFare { get; set; }
        public string StartMeterFarePerDistanceType { get; set; }
        public bool DeletedFlag { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
    }
}
