//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial_DbSkelaton.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxiBoxEntities : DbContext
    {
        public TaxiBoxEntities()
            : base("name=TaxiBoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<autogenerateinfo> autogenerateinfoes { get; set; }
        public virtual DbSet<CarType> CarTypes { get; set; }
        public virtual DbSet<Cooky> Cookies { get; set; }
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<FaresFromGatwick> FaresFromGatwicks { get; set; }
        public virtual DbSet<FixedPriced_Journies> FixedPriced_Journies { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobsOld> JobsOlds { get; set; }
        public virtual DbSet<JobsPaymentTypes_LK> JobsPaymentTypes_LK { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<SettingsFare> SettingsFares { get; set; }
        public virtual DbSet<TaxiCompany> TaxiCompanies { get; set; }
        public virtual DbSet<TownsVillage> TownsVillages { get; set; }
        public virtual DbSet<UsersBlacklist> UsersBlacklists { get; set; }
        public virtual DbSet<VehicleTypes_LK> VehicleTypes_LK { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<DriversStatu> DriversStatus { get; set; }
        public virtual DbSet<JobsNotes2> JobsNotes2 { get; set; }
        public virtual DbSet<PaxDetail> PaxDetails { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SettingsTmp> SettingsTmps { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vw_JobswithNotes> vw_JobswithNotes { get; set; }
        public virtual DbSet<vw_TownsVillages> vw_TownsVillages { get; set; }
        public virtual DbSet<vw_TownsVillages_DISTINCT> vw_TownsVillages_DISTINCT { get; set; }
        public virtual DbSet<vw_VehicleSelector> vw_VehicleSelector { get; set; }
    }
}
