//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial_DbSkelaton.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TownsVillages_DISTINCT
    {
        public string TownsVillages { get; set; }
        public Nullable<bool> DeletedFlag { get; set; }
        public int ID { get; set; }
    }
}
