//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud2_ADONet.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxiBoxEntities : DbContext
    {
        public TaxiBoxEntities()
            : base("name=TaxiBoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarType> CarTypes { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<VehicleTypes_LK> VehicleTypes_LK { get; set; }
        public virtual DbSet<vw_JobswithNotes> vw_JobswithNotes { get; set; }
        public virtual DbSet<vw_TownsVillages> vw_TownsVillages { get; set; }
        public virtual DbSet<vw_TownsVillages_DISTINCT> vw_TownsVillages_DISTINCT { get; set; }
        public virtual DbSet<vw_VehicleSelector> vw_VehicleSelector { get; set; }
    }
}
