//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DatabaseScaffolding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ID { get; set; }
        public string Book1 { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> AuthorID { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
