//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DatabaseScaffolding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AutherBook
    {
        public int ID { get; set; }
        public string Author { get; set; }
        public string Book { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> BookID { get; set; }
    }
}
