//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateExcelSheetFromDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobsNote
    {
        public int ID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> DeletedFlag { get; set; }
        public Nullable<int> JobID { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
