//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateExcelSheetFromDB.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxiBoxEntities : DbContext
    {
        public TaxiBoxEntities()
            : base("name=TaxiBoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobsNote> JobsNotes { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<vw_JobswithNotes> vw_JobswithNotes { get; set; }
    }
}
